### ISSUE TITLE
Add flag to remove V8 entries

### ISSUE THREAD

**Issue by trevnorris** [thlorenz/flamegraph#3]
Add a flag to remove entries from V8 that usually end up just polluting the graph. Something like `--no-v8-garbage`, but much better.

The lines that match the following regexp are what I'd recommend filtering out:

``` javascript
/^( __libc_start|node::Start\(| v8::internal::| Builtin:| Stub:| LoadIC:| LoadPolymorphicIC:)/
```

**Comment by thlorenz** [comment]
Fixed in version `0.4`.
[Removes internals by default and also consolidates optimized/non-optimized function calls](https://github.com/thlorenz/flamegraph/commit/69828ff2715e59737ac7a1757cc1864737d3e2b6).

![screen shot 2015-01-13 at 9 52 09 am](https://cloud.githubusercontent.com/assets/192891/5722468/4e65a052-9b0a-11e4-9d67-4a850032bc56.png)

**Comment by trevnorris** [comment]
Looks awesome!

**Comment by Andersos** [comment]
:+1:
